# Generated by Django 6.0a1 on 2026-04-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вечера')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
